name: Deploy Azure Function App via SP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install system dependencies for lxml/xmlsec
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxml2-dev \
          libxslt-dev \
          libxmlsec1-dev \
          libffi-dev \
          libssl-dev \
          gcc \
          python3-dev

    - name: Clean previous packages
      run: rm -rf .python_packages && mkdir -p .python_packages/lib/site-packages

    - name: Install Python dependencies
      run: pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: fa-weu-dev-dave-docex-01
        package: .
